ros_topics:
  image_rect: "/zed/zed_node/left/image_rect_color"

  image_left: "/zed/zed_node/left/image_rect_color"
  image_right: "/zed/zed_node/right/image_rect_color"
  depth: "/zed/zed_node/depth/depth_registered"
  camera_rgb_info: "/zed/zed_node/rgb_raw/camera_info"
  camera_left_info: "/zed/zed_node/left/camera_info"
  camera_right_info: "/zed/zed_node/right/camera_info"
  point_cloud: "/zed/zed_node/point_cloud/cloud_registered"
  odometry: "/zed/zed_node/odom"

visualization:
  point_radius: 0.005
  depth_thr_max: 0.85
  depth_thr_min: 0.4
  use_segmentation: true
  image_plane_distance: 0.2 # 카메라 프러스텀 크기 조정 가능
  traj_radius: 0.001
  baseline_m: 0.001

  # intrinsic parameters 추가 필요

# Model paths
models:
  disparity_weights_path: "models/model_best_bp2.pth"